name: assignment2_login
description: Assignment 2 - DummyJSON Login using Dio
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

flutter:
  uses-material-design: true
